### ISSUE TITLE
Mention AutoParcel in Emit immutable values

### ISSUE THREAD

**Issue by LordRaydenMK** [mgp/effective-rxjava#1]
Android is mentioned a few times in the items so maybe there should be a paragraph about [AutoParcel](https://github.com/frankiesardo/auto-parcel) [and auto-value-parcel](https://github.com/rharter/auto-value-parcel) as a tip for Android developers.

I'd be happy to submit a pull request.

**Comment by mgp** [comment]
@LordRaydenMK Thanks for the excellent suggestion! I've updated the _Emit immutable values_ item to contain such a paragraph on AutoParcel. LMK if I missed anything!
