### ISSUE TITLE
Proposal: Commit through PR

### ISSUE THREAD

**Issue by vanniktech** [mgp/effective-rxjava#4]
Would it be possible to commit through PR? This way People watching the repository would get a notification when there's something new.

In any case, big thanks for those little snippets.

**Comment by mgp** [comment]
Yes, great idea! Sorry I haven't contributed much to this recently. I've been working mostly on Java backend services for the past few months, and so I haven't had any additional RxJava insights. Eventually I will :)

**Comment by vanniktech** [comment]
No worries. If you want you can close this issue or leave it open as a reminder. Either way thanks again 👍
